name: Auto-merge Release Please PR

on:
  pull_request:
    types: [opened, reopened]

jobs:
  auto-merge:
    if: github.actor == 'release-please[bot]'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: squash
